import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";

const ibmPlex = IBM_Plex_Sans_Thai({
  subsets: ["thai"],
  weight: ["300", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibmPlex.className} antialiased`}>
        <div className="min-h-screen bg-zinc-100">
          <Navbar />
          <Hero />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
